{{- if .Values.helixCore.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helix-core.fullname" . }}
  labels:
{{ include "helix-core.labels" . | indent 4 }}
{{- if .Values.helixCore.service.labels }}
{{ toYaml .Values.helixCore.service.labels | indent 4 }}
{{- end }}
{{- if .Values.helixCore.service.annotations }}
  annotations:
{{ toYaml .Values.helixCore.service.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.helixCore.service.clusterIP }}
  clusterIP: {{ .Values.helixCore.service.clusterIP }}
{{- end }}

{{- if .Values.helixCore.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.helixCore.service.externalIPs | indent 4 }}
{{- end }}

{{- if .Values.helixCore.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.helixCore.service.loadBalancerIP }}
{{- end }}

{{- if .Values.helixCore.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.helixCore.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}

  type: {{ .Values.helixCore.service.type }}
  ports:
    - port: {{ .Values.helixCore.service.port }}
      targetPort: p4
      protocol: TCP
      name: p4
  selector:
    app.kubernetes.io/name: {{ include "helix-core.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helix-core: main

{{- if .Values.helixCore.service.sessionAffinity }}
  sessionAffinity: {{ .Values.helixCore.service.sessionAffinity }}
{{- end }}

{{- end }}