{{- if .Values.helixCore.p4admin.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: helix-core-secret-{{ include "helix-core.fullname" . }}
  labels:
{{ include "helix-core.labels" . | indent 4 }}
type: Opaque
data:
  superusername: {{ .Values.helixCore.p4admin.superusername | b64enc | quote }}
  superpassword: {{ .Values.helixCore.p4admin.superpassword | b64enc | quote }}
{{- end }}