apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helix-core.fullname" . }}
  labels:
{{ include "helix-core.labels" . | indent 4 }}
{{- if .Values.helixCore.deploymentAnnotations }}
  annotations:
    {{ toYaml .Values.helixCore.deploymentAnnotations | nindent 4 }}
{{- end }}

spec:
  replicas: {{ .Values.helixCore.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helix-core.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}

{{- if .Values.helixCore.strategy }}
  strategy:
{{ toYaml .Values.helixCore.strategy | trim | indent 4 }}
    {{ if eq .Values.helixCore.strategy.type "Recreate" }}rollingUpdate: null{{ end }}
{{- end }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helix-core.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helix-core: main
{{- if .Values.helixCore.podLabels }}
{{ toYaml .Values.helixCore.podLabels | nindent 8 }}
{{- end }}

{{- if or .Values.helixCore.podAnnotations .Values.helixCore.velero.enabled }}
      annotations:
{{- if .Values.helixCore.velero.enabled }}
        pre.hook.backup.velero.io/command: '["/opt/perforce/sbin/p4d", "-jc"]'
{{- end }}
{{- if .Values.helixCore.podAnnotations }}
{{ toYaml .Values.helixCore.podAnnotations | nindent 8 }}
{{- end }}
{{- end }}

    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: helix-core-storage
      {{- if .Values.helixCore.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.helixCore.persistentVolume.existingClaim }}{{ .Values.helixCore.persistentVolume.existingClaim }}{{- else }}helix-core-pvc-{{ include "helix-core.fullname" . }}{{- end }}
      {{- else }}
          emptyDir:
            {{- if .Values.helixCore.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.helixCore.emptyDir.sizeLimit }}
            {{- else }}
              {}
            {{- end -}}
      {{- end }}
        - name: helix-core-secret
          secret:
            secretName: {{ if .Values.helixCore.p4admin.existingSecret }}{{ .Values.helixCore.p4admin.existingSecret}}{{- else }} helix-core-secret-{{ include "helix-core.fullname" . }}{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.helixCore.image.repository }}:{{ .Values.helixCore.image.tag }}"
          imagePullPolicy: {{ .Values.helixCore.image.pullPolicy }}
          ports:
            - name: p4
              containerPort: 1666
              protocol: TCP
          livenessProbe:
            exec:
              command: ["p4", "-p", "localhost:1666", "info"]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["p4", "-p", "localhost:1666", "info"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
          {{- if .Values.helixCore.persistentVolume.enabled }}
            - mountPath: /data
              name: helix-core-storage
          {{- end }}
            - mountPath: /etc/helix-core-secret
              name: helix-core-secret
          resources:
            {{- toYaml .Values.helixCore.resources | nindent 12 }}
      {{- with .Values.helixCore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.helixCore.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.helixCore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }} 