name: On Master Changed - Docker Image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docker/**'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/docker-image-build-push.yml
        with:
          image-version: latest

