name: On Master Changed - Helm Charts

on:
  push:
    branches: [ "master" ]
    paths:
      - 'chart/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'chart/**'

  workflow_dispatch:

jobs:
  helm_chart_build_and_push:
    uses: ./.github/workflows/helm-chart-build-push.yml