name: On Master Changed - Helm Charts

on:
  push:
    branches: [ "master" ]
    paths:
      - 'chart/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'chart/**'
      
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/helm-chart-build-push.yml