name: Docker Image Latest

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/docker-image-build-push.yml
      with:
        image-version: latest

