name: On Master Changed - Docker Image

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docker/**'

  workflow_dispatch:

jobs:
  docker_build_and_push:
    uses: ./.github/workflows/docker-image-build-push.yaml
    with:
      image-version: latest
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

