name: On Release

on:
  push:
    tags:
      - 'v*'

jobs:
  docker_image_build_and_push:
    uses: ./.github/workflows/docker-image-build-push.yml
    with:
      image-version: ${{ github.event.release.tag_name }}

  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: TODO
          draft: true
          prerelease: false
